[tool.poetry]
name = "djangocourse"
version = "0.1.0"
description = "a django course"
authors = ["erj"]

[tool.poetry.dependencies]
python = "^3.11"
Django = "4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
